---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k6-test-server
  labels:
    app.kubernetes.io/instance: nginx
    app.kubernetes.io/name: techtalk-k6
    app.kubernetes.io/create-by: kamontat
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: nginx
      app.kubernetes.io/name: techtalk-k6
      app.kubernetes.io/create-by: kamontat
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: nginx
        app.kubernetes.io/name: techtalk-k6
        app.kubernetes.io/create-by: kamontat
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 200Mi
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: k6-test-server
  labels:
    app.kubernetes.io/instance: nginx
    app.kubernetes.io/name: techtalk-k6
    app.kubernetes.io/create-by: kamontat
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: k6-test-server
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: v1
kind: Service
metadata:
  name: k6-test-server
  labels:
    app.kubernetes.io/instance: nginx
    app.kubernetes.io/name: techtalk-k6
    app.kubernetes.io/create-by: kamontat
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: nginx
    app.kubernetes.io/name: techtalk-k6
    app.kubernetes.io/create-by: kamontat
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k6-test-server
  labels:
    app.kubernetes.io/instance: nginx
    app.kubernetes.io/name: techtalk-k6
    app.kubernetes.io/create-by: kamontat
  annotations:
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - host: k6-test-server.cognius.net
      http:
        paths:
          - backend:
              service:
                name: k6-test-server
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - k6-test-server.cognius.net
